[package]
name = "smol"
version = "0.1.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "WIP"
license = "MIT OR Apache-2.0"

[dependencies]
async-task = "1.3.1"
crossbeam-deque = "0.7.3"
crossbeam-queue = "0.2.1"
crossbeam-utils = "0.7.2"
futures = "0.3.4"
libc = "0.2.68"
once_cell = "1.3.1"
parking_lot = "0.10.0"
pin-utils = "0.1.0-alpha.4"
piper = { path = "piper" }
scopeguard = "1.1.0"
slab = "0.4.2"
socket2 = "0.3.11"

[target.'cfg(unix)'.dependencies]
nix = "0.17.0"

[target.'cfg(windows)'.dependencies]
wepoll-binding = "1.1.0"

[dev-dependencies]
anyhow = "1.0.27"
async-h1 = "1.0.1"
async-native-tls = "0.3.3"
async-tungstenite = { version = "0.4.2", features = ["async-native-tls"] }
base64 = "0.12.0"
http = "0.2.1"
http-types = "1.0.1"
hyper = { version = "0.13.4", default-features = false, features = ["stream"] }
num_cpus = "1.12.0"
signal-hook = "0.1.13"
tokio = { version = "0.2.13", default-features = false, features = ["rt-threaded", "time", "macros"] }
tungstenite = "0.10.1"
url = "2.1.1"
