[package]
name = "smol"
version = "0.1.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "WIP"
license = "MIT OR Apache-2.0"

[dependencies]
async-task = "1.3.0"
crossbeam-deque = "0.7.2"
crossbeam-queue = "0.1.2"
crossbeam-utils = "0.7.0"
futures-core = "0.3.3"
futures-io = "0.3.3"
futures-util = { version = "0.3.3", default-features = false, features = ["std", "io"] }
io-flag = { path = "../io-flag" }
libc = "0.2.66"
once_cell = "1.3.1"
parking_lot = "0.10.0"
pin-utils = "0.1.0-alpha.4"
piper = { path = "../piper" }
scopeguard = "1.0.0"
slab = "0.4.2"
socket2 = "0.3.11"

[target.'cfg(unix)'.dependencies]
nix = "0.16.1"

[target.'cfg(windows)'.dependencies]
wepoll-binding = "1.1.0"

[dev-dependencies]
futures = { version = "0.3.3", default-features = false, features = ["std"] }
hyper = { version = "0.13", default-features = false }
num_cpus = "1.12.0"
pin-utils = "0.1.0-alpha.4"
tokio = { version = "0.2", default-features = false }
