[package]
name = "smol"
version = "0.1.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "WIP"
license = "MIT OR Apache-2.0"

[dependencies]
async-task = "1.3.0"
crossbeam-channel = "0.4.0"
futures-core = "0.3.3"
futures-io = "0.3.3"
futures-util = { version = "0.3.3", default-features = false, features = ["std"] }
nix = "0.16.1"
num_cpus = "1.12.0"
once_cell = "1.3.1"
slab = "0.4.2"
socket2 = "0.3.11"

[dev-dependencies]
futures = { version = "0.3.3", default-features = false, features = ["std", "executor"] }
