[package]
name = "smol"
version = "0.1.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "WIP"
license = "MIT OR Apache-2.0"

[dependencies]
async-task = "3.0.0"
crossbeam = "0.7.3"
futures = { version = "0.3.4", default-features = false, features = ["std"] }
once_cell = "1.3.1"
piper = { path = "piper" }
scoped-tls = "1.0.0"
slab = "0.4.2"
socket2 = { version = "0.3.12", features = ["pair"] }

# Optional feature for seamless integration with crates depending on tokio.
# It creates a global tokio runtime and sets up its context inside smol.
#
# To use in your crate, enable the feature as follows:
# ```
# [dependencies]
# smol = { version = "1", features = ["tokio"] }
# ```
tokio = { version = "0.2.18", default-features = false, optional = true }

[target.'cfg(unix)'.dependencies]
nix = "0.17.0"

[target.'cfg(windows)'.dependencies]
wepoll-binding = "1.1.0"

[target.'cfg(windows)'.dev-dependencies]
uds_windows = "0.1.4"

[target.'cfg(target_os = "linux")'.dev-dependencies]
inotify = { version = "0.8.2", default-features = false }
timerfd = "1.1.1"

[dev-dependencies]
anyhow = "1.0.28"
async-h1 = "1.1.1"
async-native-tls = "0.3.3"
async-std = "1.5.0"
async-tungstenite = { version = "0.4.2", features = ["async-native-tls"] }
base64 = "0.12.0"
ctrlc = "3.1.4"
http = "0.2.1"
http-types = "1.2.0"
hyper = { version = "0.13.5", default-features = false, features = ["stream"] }
native-tls = "0.2.4"
num_cpus = "1.13.0"
reqwest = "0.10.4"
scraper = "0.11.0"
signal-hook = "0.1.13"
smol = { path = ".", features = ["tokio"] }
surf = "1.0.3"
tokio = { package = "tokio", version = "0.2.18", default-features = false, features = ["rt-threaded"] }
tungstenite = "0.10.1"
url = "2.1.1"
