[package]
name = "smol"
version = "0.1.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "WIP"
license = "MIT OR Apache-2.0"

[dependencies]
async-task = "1.3.0"
crossbeam-channel = "0.4.0"
crossbeam-utils = "0.7.0"
futures-core = "0.3.3"
futures-io = "0.3.3"
futures-util = { version = "0.3.3", default-features = false, features = ["std", "io"] }
once_cell = "1.3.1"
parking_lot = "0.10.0"
pin-utils = "0.1.0-alpha.4"
slab = "0.4.2"
socket2 = "0.3.11"
libc = "0.2.66"

[target.'cfg(unix)'.dependencies]
nix = "0.16.1"

[target.'cfg(windows)'.dependencies]
wepoll-binding = "1.1.0"

[dev-dependencies]
futures = { version = "0.3.3", default-features = false, features = ["std"] }
hyper = { version = "0.13", default-features = false }
num_cpus = "1.12.0"
pin-utils = "0.1.0-alpha.4"
tokio = { version = "0.2", default-features = false }

async-tungstenite = {git="https://github.com/sdroege/async-tungstenite"}
async-tls = {git="https://github.com/async-rs/async-tls"}
url = "*"
