name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
  loc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install cargo-count
        run: cargo install cargo-count

      - name: Run cargo count
        # '-a --exclude=$(cat .gitignore)' necessary to work around:
        # https://github.com/kbknapp/cargo-count/issues/36
        run: cargo count -l rs -a --exclude=$(cat .gitignore) src
